export const TYPES = {
  SET_NAME: 'SET_NAME',
  SET_NAME_SAGA_REQUEST: 'SET_NAME_SAGA_REQUEST',
  SET_NAME_SAGA_SUCCESS: 'SET_NAME_SUCCESS',
  SET_NAME_SAGA_FAILURE: 'SET_NAME_FAILURE',
  SET_NAME_SAGA_CONFIRM: 'SET_NAME_SAGA_CONFIRM',

  SET_SNACKBAR_OPEN: 'SET_SNACKBAR_OPEN',
};